import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">One</Link>
        </li>
        <li>
          <Link to="/page">Page</Link>
        </li>
        <li>
          <Link to="/page1">Page1</Link>
        </li>
        <li>
          <Link to="/windows">Windows</Link>
        </li>
        <li>
          <Link to="/one1">One1</Link>
        </li>
        <li>
          <Link to="/four">Four</Link>
        </li>
        <li>
          <Link to="/one2">One2</Link>
        </li>
        <li>
          <Link to="/page2">Page2</Link>
        </li>
        <li>
          <Link to="/macone">MacOne</Link>
        </li>
        <li>
          <Link to="/two">Two</Link>
        </li>
        <li>
          <Link to="/five">Five</Link>
        </li>
        <li>
          <Link to="/two1">Two1</Link>
        </li>
        <li>
          <Link to="/mactwo">MacTwo</Link>
        </li>
        <li>
          <Link to="/three">Three</Link>
        </li>
        <li>
          <Link to="/componentsetregistration">ComponentSetRegistration</Link>
        </li>
        <li>
          <Link to="/one3">One3</Link>
        </li>
        <li>
          <Link to="/windows1">Windows1</Link>
        </li>
        <li>
          <Link to="/two2">Two2</Link>
        </li>
        <li>
          <Link to="/page3">Page3</Link>
        </li>
        <li>
          <Link to="/two3">Two3</Link>
        </li>
        <li>
          <Link to="/three1">Three1</Link>
        </li>
        <li>
          <Link to="/two4">Two4</Link>
        </li>
        <li>
          <Link to="/four1">Four1</Link>
        </li>
        <li>
          <Link to="/macthree">MacThree</Link>
        </li>
        <li>
          <Link to="/five1">Five1</Link>
        </li>
        <li>
          <Link to="/one4">One4</Link>
        </li>
        <li>
          <Link to="/three2">Three2</Link>
        </li>
        <li>
          <Link to="/two5">Two5</Link>
        </li>
        <li>
          <Link to="/five2">Five2</Link>
        </li>
        <li>
          <Link to="/mac">Mac</Link>
        </li>
        <li>
          <Link to="/three3">Three3</Link>
        </li>
        <li>
          <Link to="/one5">One5</Link>
        </li>
        <li>
          <Link to="/page4">Page4</Link>
        </li>
        <li>
          <Link to="/three4">Three4</Link>
        </li>
        <li>
          <Link to="/page5">Page5</Link>
        </li>
        <li>
          <Link to="/macone1">MacOne1</Link>
        </li>
        <li>
          <Link to="/six">Six</Link>
        </li>
        <li>
          <Link to="/page6">Page6</Link>
        </li>
        <li>
          <Link to="/one6">One6</Link>
        </li>
        <li>
          <Link to="/seven">Seven</Link>
        </li>
        <li>
          <Link to="/mactwo1">MacTwo1</Link>
        </li>
        <li>
          <Link to="/one7">One7</Link>
        </li>
        <li>
          <Link to="/page7">Page7</Link>
        </li>
        <li>
          <Link to="/five3">Five3</Link>
        </li>
        <li>
          <Link to="/page8">Page8</Link>
        </li>
        <li>
          <Link to="/six1">Six1</Link>
        </li>
        <li>
          <Link to="/seven1">Seven1</Link>
        </li>
        <li>
          <Link to="/four2">Four2</Link>
        </li>
        <li>
          <Link to="/one8">One8</Link>
        </li>
        <li>
          <Link to="/four3">Four3</Link>
        </li>
        <li>
          <Link to="/six2">Six2</Link>
        </li>
        <li>
          <Link to="/seven2">Seven2</Link>
        </li>
        <li>
          <Link to="/page9">Page9</Link>
        </li>
        <li>
          <Link to="/one9">One9</Link>
        </li>
        <li>
          <Link to="/two6">Two6</Link>
        </li>
        <li>
          <Link to="/three5">Three5</Link>
        </li>
        <li>
          <Link to="/four4">Four4</Link>
        </li>
        <li>
          <Link to="/one10">One10</Link>
        </li>
        <li>
          <Link to="/two7">Two7</Link>
        </li>
        <li>
          <Link to="/one11">One11</Link>
        </li>
        <li>
          <Link to="/two8">Two8</Link>
        </li>
        <li>
          <Link to="/three6">Three6</Link>
        </li>
        <li>
          <Link to="/page10">Page10</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
